CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT TEXT,
    PRICE REAL
);

INSERT INTO PRODUCTS VALUES
    ('1','RICE', '1','1','10 SACKS',18),
    ('2','BREAD','1','1','2 LOAVES',12),
    ('3','JUICE','1','2','12-550 ML BOTTLES',22),
    ('4','EGGS','2','2','3 TRAYS',19),
    ('5','YOGHURT','2','2','25 BOXES',17.35);

SELECT DISTINCT SUPPLIER_ID FROM PRODUCTS; 

SELECT COUNT(PRODUCT_ID) AS Product_Count
FROM PRODUCTS;

SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS;    

SELECT SUM(PRICE) AS Total_Price
FROM PRODUCTS;

SELECT MAX(PRICE) AS Most_expensive FROM PRODUCTS;
SELECT MIN(PRICE) AS Least_expensive FROM PRODUCTS;