CREATE TABLE IF NOT EXISTS RESTRAURANT (
    ROLL_NO TEXT PRIMARY KEY,
    FOOD TEXT,
    PRICE INTEGER,
    NUMBEROFORDERS TEXT
);

INSERT INTO RESTRAURANT VALUES
    ('678', 'fries', 2000, '9'),
    ('345', 'burger', 1500, '7'),
    ('163', 'pizza', 3500, '3'),
    ('456', 'soda', 170, '5'),
    ('851', 'chicken', 2630, '6');

SELECT *
FROM RESTRAURANT
WHERE  FOOD NOT LIKE 'p%';

SELECT * FROM RESTRAURANT ORDER BY NUMBEROFORDERS ASC;

SELECT * FROM RESTRAURANT ORDER BY NUMBEROFORDERS DESC;

SELECT * FROM RESTRAURANT WHERE NUMBEROFORDERS  < 9;

SELECT * FROM RESTRAURANT ORDER BY NUMBEROFORDERS DESC LIMIT 4;

SELECT * FROM RESTRAURANT WHERE PRICE > 1000;
SELECT * FROM RESTRAURANT WHERE PRICE < 1000;

SELECT SUM(PRICE) AS Total_Price
FROM RESTRAURANT;

SELECT MAX(PRICE) AS Most_expensive FROM RESTRAURANT;
SELECT MIN(PRICE) AS Least_expensive FROM RESTRAURANT ;