CREATE TABLE IF NOT EXISTS NOBEL_WIN(
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT

);

INSERT INTO NOBEL_WIN VALUES
    (1970, 'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),
    (1970, 'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),
    (1971, 'PHYSICS','PAUL','FRANCE','SCIENTIST'),
    (1971, 'CHEMISTRY','HAMITON','SWEDEN','LINGUIST'),
    (1972, 'LITERATURE','BERNARD KELSON','GERMANY','ECONOMIST'),
    (1972, 'ECONOMICS','JOSEPH','RUSSIA','ECONOMIST');
    
SELECT *
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';
SELECT * FROM NOBEL_WIN ORDER BY COUNTRY ASC;
SELECT * FROM NOBEL_WIN ORDER BY COUNTRY DESC;
SELECT * FROM NOBEL_WIN GROUP BY SUBJECT;
SELECT * FROM NOBEL_WIN GROUP BY COUNTRY;
SELECT COUNT (WINNER) FROM NOBEL_WIN WHERE SUBJECT LIKE 'P%' GROUP BY SUBJECT;