f1 = open('C:/Users/Owner/Downloads/Python programmes/myfile.txt','r')
print(f1.read(12))
f1.close()
f1 = open('C:/Users/Owner/Downloads/Python programmes/myfile.txt','a')
f1.write("Good morning.How are you today?")
f1.close()
f2 = open('C:/Users/Owner/Downloads/Python programmes/newfile.txt','w')
f2.write("This file is just created")
f2.close()
f2 = open('C:/Users/Owner/Downloads/Python programmes/newfile.txt','r')
print(f2.readline())
f2.close()