CREATE TABLE IF NOT EXISTS FITNESSRECORDS (
    NAME TEXT PRIMARY KEY,
    TYPEOFEXERCISE TEXT,
    CALORIES_BURNED TEXT,
    DURATION TEXT,
    AGE INTEGER
);

INSERT INTO FITNESSRECORDS VALUES
('Samara','Jumping rope (fast)','490 cal','30 min',24),
('Peter','Strength training','300 cal','1 hour',34),
('Maria','Yoga (Vinyasa)','100 cal','30 min',29),
('Dhruv','Running (6mph)','173 cal','15 min',36),
('Alice','Hula hooping','300 cal','1 hour',40),
('Stella','Walking (brisk)','125 cal','30 min',38);

SELECT * FROM FITNESSRECORDS;

SELECT * FROM FITNESSRECORDS WHERE AGE > 30;

SELECT SUM(DURATION) AS Total_time
FROM FITNESSRECORDS;

SELECT *
FROM FITNESSRECORDS
WHERE NAME LIKE 'S%';


SELECT * FROM FITNESSRECORDS WHERE TYPEOFEXERCISE  = 'Hula hooping';

SELECT * FROM FITNESSRECORDS WHERE TYPEOFEXERCISE LIKE '%Jumping%';

SELECT * FROM FITNESSRECORDS ORDER BY AGE DESC ;

SELECT * FROM FITNESSRECORDS ORDER BY CALORIES_BURNED ASC ;

SELECT * FROM FITNESSRECORDS WHERE CALORIES_BURNED ='300 cal' AND DURATION= '1 hour';

SELECT MAX(CALORIES_BURNED) AS Most_calories FROM FITNESSRECORDS;
SELECT MIN(CALORIES_BURNED) AS Least_calories FROM FITNESSRECORDS;