CREATE TABLE IF NOT EXISTS STUDENTRECORDS(
    Student_id TEXT PRIMARY KEY,
    NAME TEXT,
    GENDER TEXT,
    RESULTS TEXT
);
INSERT INTO STUDENTRECORDS VALUES
    ('4509','James','boy','98%'),
    ('9288','Charles','boy','76%'),
    ('9303','Jane','girl','58%'),
    ('5674','Samara','girl','46%'),
    ('8745','Sophia','girl','80%'),
    ('2509','Matthew','boy','43%');

SELECT *
FROM STUDENTRECORDS
WHERE NAME LIKE 'S%';

SELECT * FROM STUDENTRECORDS ORDER BY RESULTS DESC; 

SELECT MAX(RESULTS) AS MAXIMIUM_RESULTS FROM STUDENTRECORDS;
SELECT MIN(RESULTS) AS MINIMUM_RESULTS FROM STUDENTRECORDS;

SELECT * FROM STUDENTRECORDS ORDER BY Student_id ASC;

SELECT * FROM STUDENTRECORDS WHERE RESULTS > '40%';
SELECT COUNT(Student_id) FROM STUDENTRECORDS WHERE GENDER = 'girl';