CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

INSERT INTO STUDENT VALUES
('1','RAM','DELHI','*****',18),
('2','ISABELLE','TANZANIA','*****',18),
('3','ZARA','SOUTH AFRICA','*****',20),
('4','PETER','SAUDI ARABIA','*****',18),
('5','TOM','SWITZERLAND','*****',20),
('6','ELLA','KENYA','*****',18);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE =18 AND ADDRESS = 'DELHI';